version: '3'

services:
    database:
        container_name: ebms-mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017

    api:
        container_name: ebms-api
        image: api
        restart: always
        build: ./api
        ports:
            - 3000:5000
        environment:
            - PSWD=888888
            - USRNAME=admin
            - PORT=5000
            - IP=0.0.0.0
            - GATEWAYIP=86.5.168.26
            - GATEWAYPORT=8080
        links:
            - database
            # api://ebms-api:5000

    website:
        container_name: ebms-UI
        restart: always
        build: ./ebms-frontend
        ports:
           - 80:80
        links:
            - api
