name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Dependancies
      run: npm install
      working-directory: ./ebms-frontend
    - name: Build
      run: npm run build
      working-directory: ./ebms-frontend
    - name: Docker verfication
      run: docker-compose up --build
