name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        node-version: [ 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Build frontend 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          cd ebms-midi
          npm install
          npm run build --if-present
        env:
          CI: true
